name = "facebookdownbot"
main = "index.mjs" 
compatibility_date = "2025-11-01" 

compatibility_flags = [
    "nodejs_compat" 
]

# අමතර Workers configuration තිබේ නම් ඒවා මෙතනට

# Workers Logs සහ Tracing සක්‍රීය කිරීම සඳහා
[observability]
enabled = true
